Ina test branch
warisa-r/ShockwaveDetection.jl pull request #22
Opened 2024-09-24 16:31 UTC by dzhingarska

comparing the shock positions over time of flow data and flow data with additional noise

2024-09-24 17:07 UTC, warisa-r requested changes

2024-09-24 17:07 UTC, warisa-r commented on analysis/noise.jl
> +        # Calculate the differences
False detection (fewer points or more points detected at wrong places) can be more fatal than detecting points that are further away. I think we should take a look at 

1. How many false detections do we get
2.**How much does this affect the final curves** since it is natural for simple gradient filter to detect more/less points when gradients of some points are decreased or increased. But are the final curves/fit which are our method of preventing these kinds of numerical artefacts still there?

2024-09-24 17:07 UTC, warisa-r commented on analysis/noise.jl
> +function compare_shock_clusters_over_time(original_clusters, noisy_clusters)
This function looks quite useful. Could we use them along comparing the fits to actually see how devastating noises are to our algorithm?

2024-09-24 17:12 UTC, warisa-r requested changes

2024-09-24 17:12 UTC, warisa-r commented on analysis/noise.jl
> +function apply_noise_to_flow(flow_data::FlowData, noise_data::NoiseData)
Could we try adding noise to some properties in some cases and if things go differently?

2024-09-24 17:12 UTC, warisa-r commented on analysis/noise.jl
> +    intensity::Float64
Not a priority but can intensity be type generic?

2024-09-24 17:12 UTC, warisa-r commented on analysis/noise.jl
> +    diffs = Float64[]
Same question with type generic-ness. But also not a priority

2024-09-24 17:12 UTC, warisa-r commented on analysis/noise.jl
> +    if isempty(diffs)
I meant this for 2D but for 1D then shock point comparison is very fair.

2024-09-24 17:12 UTC, warisa-r commented on examples/sod_shock_tube_1d.jl
>  using ShockwaveDetection
No changes according to main. Could we get rid of this commit?

2024-09-24 17:13 UTC, warisa-r commented
#7

2024-09-25 09:45 UTC, dzhingarska commented on analysis/noise.jl
> +function apply_noise_to_flow(flow_data::FlowData, noise_data::NoiseData)
What do you mean exactly?

2024-09-25 14:38 UTC, warisa-r commented on analysis/noise.jl
> +function apply_noise_to_flow(flow_data::FlowData, noise_data::NoiseData)
For example: Try adding boise to pressure and density and leave the velocity field alone

2024-09-27 05:28 UTC, warisa-r requested changes

2024-09-27 05:28 UTC, warisa-r commented on analysis/noise.jl
> +        elseif isempty(noisy)
I understand what Inf for empty detection in noisy is if it wasn't empty in the original array. But isn't this an extreme result in comparison to the conditions below?

Case 1
For example: original data detection [1] noisy data detection []
Penalty: Inf -> Invalid detection

Case 2
original data: detection [1,55]
noisy data: detection [55]
Penalty: (27.5 - 55)^2

In both cases, shock in 1 place is missing entirely but the penalty is so starkly different for some reason.

I initially thought about clustering the detected positions in 1D to help detect the consistency and compare each cluster of points. For now, I don't think this is a valid way of quantifying how noise affects our results in 1D. Could you come up with some other methods? Or simply let me know if I misunderstood how this work.

2024-09-27 05:28 UTC, warisa-r commented on analysis/noise.jl
> +original_fits = [[Fitting(params1), nothing], [Fitting(params2), Fitting(params3)]]
This isn't how Fitting stores information. Could you check out the struct for the documentation of this function?

2024-09-27 05:28 UTC, warisa-r commented on analysis/noise.jl
> +        padding = fill(0.0, length(original_params) - length(noisy_params))
The issue is that this would only work if all of our models have only 1 important parameter. But that is not the case for most of our essential models (the majority and the ones that are fitted most are parabola, circle, and line, all of which have 2-3 parameters)

And also, what if in the case where the model actually only has 1 parameter like `hline` and `vline` (check out sod tube 2d case) and the parameter is 0.0. Then the padded value is a spot-on guess and doesn't signify whatsoever that the algorithm fails to fit something even though it does.

Even though the number in the `missing_count` does vaguely say something but the mean you get from this part of the code is tampered.

2024-09-27 05:28 UTC, warisa-r commented on analysis/noise.jl
> +    inf_ratio = inf_count / length(original_positions)  # Calculate ratio based on original count
what if the length of the original positions is 0? This isn't a priority but it is something to look out for.

2024-09-27 05:28 UTC, warisa-r commented on analysis/noise.jl
> +    if isempty(original_params) || isempty(noisy_params)
Fit result will never be empty if there is a cluster of points. If there isn't any shock formed in that frame because there isn't any e.g. supersonic inflow in some of the simulation instances since it will be introduced later, does this mean we can't compare fits of the entire simulation run?

What would be the reason to throw an error here?

2024-09-27 05:38 UTC, warisa-r commented
@dzhingarska Could you please resolve the things you already fixed? And I think that this task will take a while. In my humble opinion, it isn't easy to quantify false detection correctly and logically when we take a close look at the scenarios we have. Initially, I thought this would take around a month or something no shorter than that. It has been a month and maybe it's better if we view what we want to do more realistically. 

We could move on to the report so we can finally be done with the software since we have been doing this since the beginning of June which is quite a long time already.

It is not a big deal, but if we can get this working, that'd be cool.

Let me know what you think and plan to do :)

2024-09-27 19:45 UTC, dzhingarska commented on analysis/noise.jl
> +    if isempty(original_params) || isempty(noisy_params)
fit result is not going to be empty, the condition is not met but I thought it should be there rather for the overall look of the function, and yes we cannot compare flow without shocks and we also do not want to, the purpose of this function is also not that

2024-09-27 19:46 UTC, dzhingarska commented on analysis/noise.jl
> +    inf_ratio = inf_count / length(original_positions)  # Calculate ratio based on original count
it practically never happens but I can still handle this case if necessary, but I don't think it is for our simulation

2024-09-27 19:48 UTC, dzhingarska commented on analysis/noise.jl
> +original_fits = [[Fitting(params1), nothing], [Fitting(params2), Fitting(params3)]]
my bad

2024-09-27 20:15 UTC, dzhingarska commented on analysis/noise.jl
> +        padding = fill(0.0, length(original_params) - length(noisy_params))
I will fix the issue with hline and vline with padding with special value like NaN. This will now give a clear distinction between models that fit poorly (high RMSE) and models where parameters were simply missing. Additionally, I extract all the parameters not just the first one, that was my bad.

2024-09-27 20:48 UTC, dzhingarska commented on analysis/noise.jl
> +                    push!(params, fit.parameters[1])  # Assuming you want the first parameter
I am extracting all parameters now.

2024-09-27 20:48 UTC, dzhingarska commented on examples/sod_shock_tube_1d.jl
> +# Create a NoiseData instance
ok

2024-09-27 20:49 UTC, dzhingarska commented on analysis/noise.jl
> +        elseif isempty(noisy)
You are right, the penalty seems to be off. I can do so that if a shock is missing in one array but detected in the other, rather than assigning an Inf penalty, I can calculate a penalty based on the average distance between other shocks in the data.
This would make the penalty for missing shocks proportionate to the size of the deviations that occur when shocks are detected but slightly misplaced.

2024-09-27 21:44 UTC, dzhingarska commented on analysis/noise.jl
>          else
check the comment below

2024-09-27 21:47 UTC, dzhingarska commented on examples/sod_shock_tube_1d.jl
> +# Create a NoiseData instance
I left it there because you asked not to change the file last time, but I can remove the noise data instance

2024-09-28 01:35 UTC, warisa-r commented on examples/sod_shock_tube_1d.jl
> +# Create a NoiseData instance
I meant, please don’t commit to this file.

2024-09-28 03:09 UTC, warisa-r requested changes

2024-09-28 03:09 UTC, warisa-r commented on analysis/noise.jl
> +                deleteat!(noisy, closest_idx)
This algorithm looks fine to me. My problem with this kind of penalty (even though it is fair) is that now the difference is bloated with a large penalty and this renders the difference in the close noisy positions and the original positions trivial (occupying floating point spaces and pushing the smaller values away from storage).

Could we not add large penalties and only count missing shock positions? That would lessen the meaning of diffs calculated here but I think that there is a limit to what we can get out of arithmetic operations.

2024-09-28 03:09 UTC, warisa-r commented on analysis/noise.jl
> +    return rmse, missing_count
Please try this with `funky_square.celltape` with a gradient threshold of `0.05`. There are all sorts of clusters and fit should show up.  If this algorithm is working then it should run fine with this case.

2024-09-28 19:56 UTC, dzhingarska commented on src/ShockwaveDetection.jl
> +export Fitting, FittingAlgo, fit_shock_clusters_over_time, calculate_normal_vector
removed

2024-09-28 20:14 UTC, dzhingarska commented on analysis/noise.jl
> +                deleteat!(noisy, closest_idx)
done, no more large penalties, just missing_count

2024-09-28 23:13 UTC, dzhingarska commented on analysis/noise.jl
> +    differences = original_params .- noisy_params
You have a point there, actually I comparing the parameters of the fit does not make so much sense as I was expecting and it seems another approach is needed. Now instead of focusing on the parameters themselves, we can compare how well the models fit the data points (original_shock_positions_over_time and noisy_shock_positions_over_time). The new solution compares the model residuals (the difference between the original data points and the fitted data) rather than the raw parameters. Check it out and suggest improvements or feel free to adjust as well.

2024-09-29 08:08 UTC, warisa-r requested changes

2024-09-29 08:08 UTC, warisa-r commented on analysis/noise.jl
> +   - If no close match is found, the function applies a **large penalty** (set to `100.0`) to reflect a significant mismatch or false positive.
The docstring should be updated as this has changed, right? (Not a priority)

2024-09-29 08:08 UTC, warisa-r commented on analysis/noise.jl
> +                deleteat!(noisy, closest_idx)
This looks good! Could you document the result that you get from applying noise and calling this function with 1D simulation scenarios?

2024-09-29 08:08 UTC, warisa-r commented on analysis/noise.jl
> +        if isempty(original_shock_positions_over_time[t])
Fit should be compared to its respective cluster, not all the shock points in 1-time frame. Since in 1 time frame we could be trying to fit 4 curves and comparing all the points to only 1 left curve will result in a false outcome of bloated residuum (see the last frames of sod shock orb for example)

2024-09-29 15:14 UTC, dzhingarska commented on analysis/noise.jl
> +   - If no close match is found, the function applies a **large penalty** (set to `100.0`) to reflect a significant mismatch or false positive.
true, done

2024-09-30 03:59 UTC, warisa-r reviewed
I think things should be working quite smoothly now if you test it with shock orb. But if it doesn't, totally up to you if you want to test it. Apart from some comments here about the comparison logic(which might be wrong from my side), I think all should be functioning :D

2024-09-30 03:59 UTC, warisa-r commented on analysis/noise.jl
> +            noisy_residuals = calculate_residuals(noisy_fit[t][i], noisy_data_points)
Correct me if I'm wrong here but isn't this line supposed to be

`noisy_residuals = calculate_residuals(noisy_fit[t][i], original_data_points)` ?

We want to see how much the curve deviated from its original points (original data) e.g. how sensitive the curve is compared to the original findings. Since if we compared the noisy fit to the noisy data points, it is very likely we might get a new far-off curve that fit the noises better as the Levenberg-Marquardt algorithm does naturally.

What we rather want to see is how clustering, or different kernels, or the concept of curves themselves even, can help preserve the original shock curves.

2024-09-30 03:59 UTC, warisa-r commented on analysis/noise.jl
> +            if length(original_residuals) != length(noisy_residuals)
This is very cautious of you :) However, I haven't encountered this before and am not sure where this can come from. So I'm also not sure if this is a case we can encounter if we have the same amount of data points we are comparing. But in the case that noisy shock points and original shock points don't match maybe we can find the difference in the second norm of both residues?

namely

`norm(original_residuals,2) - norm(noisy_residuals,2)`

This way we are performing a scalar operation but as mentioned before, I am not so sure about this as I haven't experienced this problem before

2024-09-30 03:59 UTC, warisa-r commented on analysis/noise.jl
> +    original_clusters = ShockwaveDetection.cluster_shock_points(dbscan_algo, original_shock_positions_over_time, flow_data)
Not necessarily a priority but shock clusters can already be accessed from ShockDetectionResult as an attribute called

`shock_clusters_over_time`

2024-09-30 14:28 UTC, dzhingarska commented on analysis/noise.jl
> +            noisy_residuals = calculate_residuals(noisy_fit[t][i], noisy_data_points)
oh, I have totally overseen that, I think you are right. Thanks.

2024-09-30 14:54 UTC, dzhingarska commented on examples/sod_shock_tube_2d.jl
> +#create_heatmap_evo_with_shock(flow_data, detection, :density_field, true, false)
Can I just copy it from main and commit, since it would be complicated reverting commits just because of this?

2024-09-30 23:37 UTC, dzhingarska commented
I think we can upload to the registry now, if there is something more, it won't be relevant for the user.

2024-10-01 14:50 UTC, warisa-r approved these changes

2024-10-01 14:51 UTC, merged